---
title: "lab5"
author: "Котов Иван, РИ-440004"
date: '17 декабря 2017 г '
output: html_document
---

```{r}
#Пользуясь примером из лекции файл (5.0.R), проанализируйте данные
#о возрасте и физ. характеристиках молюсков
#https://archive.ics.uci.edu/ml/datasets/abalone
data <- read.csv("https://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data", header=TRUE, sep=",")
summary(data)
colnames(data)
colnames(data) <- c("sex", "length", "diameter", "height", 
                "whole_weight", "shucked_weight",
                "viscera_weight", "shell_weight", "rings")

colnames(data)
data$sex <- factor(c("Female", "Infant", "Male")[data$sex])
summary(data)
par(mfrow=c(1,3)) 
hist(data$diameter, main = "Диаметр, мм")
hist(data$height, main = "Высота, мм")
hist(data$whole_weight, main = "Полный вес, гр")
#Видим асимметрию https://en.wikipedia.org/wiki/Skewness
#и выбросы (от них нужно избавиться)

#Визулизируем возможные зависимости
par(mfrow=c(1,2)) 
plot(data$diameter, data$whole_weight,'p',main = "Зависимость веса от диаметра")
plot(data$height, data$whole_weight,'p',main = "Зависимость веса от высоты")

#Хорошо видна зависимость, нужно её исследовать
#построить линейные модели при помощи функции lm, посмотреть их характеристики:
```

```{r}
#Линейная модель зависимости веса от диаметра
linear.model.wheight.diameter<-lm(whole_weight~diameter,data=data)
linear.model.wheight.diameter
summary(linear.model.wheight.diameter)
plot(linear.model.wheight.diameter)
```

```{r}
#Линейная модель зависимости веса от высоты
linear.model.weight.height<-lm(whole_weight~height,data=data)
linear.model.weight.height
summary(linear.model.weight.height)
plot(linear.model.weight.height)
```


```{r}
#избавиться от выборосов, построить ещё модели и проверить их:
#Избавляемся от отклонений, ограничивая по весу от 0.02 до 0.5 и по диаметру до 0.6:
data.noout<-data[data$height<0.5&data$height>0.02&data$diameter<0.6,]

linear.model.weight.height.clean<-lm(whole_weight~height,data=data.noout)
linear.model.weight.height.clean
summary(linear.model.weight.height.clean)
plot(linear.model.weight.height.clean)

linear.model.wheight.diameter.clean<-lm(whole_weight~diameter,data=data.noout)
linear.model.wheight.diameter.clean
summary(linear.model.wheight.diameter.clean)
plot(linear.model.wheight.diameter.clean)

```


```{r}
#разделить массив данных на 2 случайные части
#подогнать модель по первой части:
odds <- seq(1, nrow(data.noout), by=2)
data.in <- data.noout[odds,]
data.out <- data.noout[-odds,]
data.in<-data.in
point<-round(runif(1,max=2078)); 
data.in<-data.in[-point,]; 
```

```{r}
#Линейная модель с половинным набором данных:
linear.model.train<-lm(whole_weight~.-shucked_weight-viscera_weight-shell_weight,data=data.in)
linear.model.train
summary(linear.model.train)
plot(linear.model.train)
```

```{r}
#Разделим массив данных и попробуем предсказать значения:
data.predict <- predict (linear.model.train)
cor (data.in$whole_weight, data.predict)
plot (data.in$whole_weight, data.predict)
#Корреляция: 0.9358035
```

```{r}
#спрогнозировать (функция predict) значения во второй части
#проверить качество прогноза:
data.predict.out <- predict (linear.model.train, data.out)
cor (data.out$whole_weight, data.predict.out)
plot (data.out$whole_weight, data.predict.out)
#Корреляция: 0.9399851
```
